In [1]:
#Import needed modules

import pandas as pd
from pandas import DataFrame, read_csv
from bs4 import BeautifulSoup as soup
from pretty_html_table import build_table

In [2]:
#Load clean csv to manipulate

file_to_load = "..\data_cleaning\export\movie_db.csv"
lowest_budget = pd.read_csv(file_to_load)
lowest_budget.head(5)

,index,title,id,release_date,cast,percentage_top_5_female_led,total_top_5_female_led,total_female_actors,total_actors,percentage_female_cast,...,original_language,languages,total_genres,genres,runtime,revenue,budget,budget_bins,country_language_x,country_language_y
0,0,The Suicide Squad,436969,7/28/21,Margot Robbie Idris Elba John Cena Joel Kinnam...,0.2,1,11,44,0.250000,...,en,English Spanish,4,Action Adventure Fantasy Comedy,132,118084747,180000000,151m to 380m,United States,United States
1,1,Jungle Cruise,451048,7/28/21,Dwayne Johnson Emily Blunt Edgar Ramírez Jack ...,0.2,1,11,67,0.164179,...,en,English Spanish Portuguese,4,Adventure Fantasy Comedy Action,127,154342554,200000000,151m to 380m,United States,United States
2,2,Black Widow,497698,7/7/21,Scarlett Johansson Florence Pugh Rachel Weisz ...,0.6,3,33,96,0.343750,...,en,English Russian,4,Action Adventure Thriller Science Fiction,134,367799531,200000000,151m to 380m,United States,United States
3,3,Space Jam: A New Legacy,379686,7/8/21,LeBron James Don Cheadle Cedric Joe Jeff Bergm...,0.0,0,9,37,0.243243,...,en,English,4,Animation Comedy Family Science Fiction,115,144882738,161900000,151m to 380m,United States,United States
4,4,The Boss Baby: Family Business,459151,7/1/21,Alec Baldwin James Marsden Amy Sedaris Jeff Go...,0.4,2,4,25,0.160000,...,en,English,4,Animation Comedy Adventure Family,107,70324240,82000000,51m to 150m,United States,United States

In [3]:
#return columns needed for web page build

lowest_total_budget = lowest_budget.loc[:, ["title", "budget", "popularity"]]
lowest_total_budget.head(5)
#lowest_total_budget.columns = ["Title", "Budget", "Populartiy"]

                            title     budget  popularity
0               The Suicide Squad  180000000    7243.123
1                   Jungle Cruise  200000000    6680.739
2                     Black Widow  200000000    2564.501
3         Space Jam: A New Legacy  161900000    2327.176
4  The Boss Baby: Family Business   82000000    1759.371

In [4]:
#Creating DataFrame for "Total Lowest Budget Movies"

lowest_budget_sorted = lowest_total_budget.sort_values("budget").nsmallest(25, "budget")
#lowest_budget_sorted2 = lowest_budget_sorted.drop(['budget_bins'], axis=1)
print(lowest_budget_sorted)

                               title  budget  popularity
2868               Sex and Death 101       5      13.981
3157  Chestnut: Hero of Central Park       6      12.673
379                      Brian Banks      10      56.422
2199                         Sanctum      30      17.091
2881     Rugrats in Paris: The Movie      30      13.908
666                      Sí, Mi Amor    5000      39.666
2476                          Primer    7000      15.648
2545          King Kong vs. Godzilla   12000      15.284
3399                 One Missed Call   20000      11.922
2723             One Cut of the Dead   30000      14.530
930          The Blair Witch Project   60000      32.225
3078                          Vixen!   76000      13.012
748     The Texas Chain Saw Massacre   85000      36.719
2054                   A Ghost Story  100000      17.981
1220               Facing the Giants  100000      26.620
2622                   Another Earth  100000      14.960
1833                     The Gallows  100000      19.745
1722                        Stitches  100000      20.636
2083        Night of the Living Dead  114000      17.821
994                   The Villainess  125000      30.600
2417           The Way of the Dragon  130000      15.931
2049                      Open Water  130000      18.014
524                        Megalodon  130178      45.816
2439            In the Mood for Love  150000      15.823
1157              Children of Heaven  180000      27.619

In [5]:
#Creating DataFrame for Most Popular Low Budget Movies"


popular_movie = lowest_total_budget[(lowest_total_budget["budget"] <= 1000000)]
clean_popular_movie = popular_movie.sort_values("popularity", ascending=False)
print(clean_popular_movie)

                           title   budget  popularity
42    The Last: Naruto the Movie  1000000     216.958
310                        Bambi   858000      64.261
343     Dragon Ball Super: Broly  1000000      60.312
374                        Dumbo   812000      57.254
379                  Brian Banks       10      56.422
...                          ...      ...         ...
3395          The Maltese Falcon   375000      11.937
3399             One Missed Call    20000      11.922
3405                   High Noon   730000      11.903
3414              Sleepaway Camp   350000      11.869
3420             Meet the Blacks   900000      11.845

[105 rows x 3 columns]

In [6]:
#Creating DataFrame for least Popular Low Budget Movies

popular_movie = lowest_total_budget[(lowest_total_budget["budget"] <= 1000000)]
clean_least_popular = popular_movie.sort_values("popularity")
print(clean_least_popular)

                           title   budget  popularity
3420             Meet the Blacks   900000      11.845
3414              Sleepaway Camp   350000      11.869
3405                   High Noon   730000      11.903
3399             One Missed Call    20000      11.922
3395          The Maltese Falcon   375000      11.937
...                          ...      ...         ...
379                  Brian Banks       10      56.422
374                        Dumbo   812000      57.254
343     Dragon Ball Super: Broly  1000000      60.312
310                        Bambi   858000      64.261
42    The Last: Naruto the Movie  1000000     216.958

[105 rows x 3 columns]

In [7]:
lowest_budget_sorted.columns = ["Title", "Budget", "Populartiy"]
#lowest_budget_html = lowest_budget_sorted.to_html()

html_low_budget_sorted = build_table(lowest_budget_sorted, 'blue_dark')
print(html_low_budget_sorted)

#popular_movie
#popular_movie.columns = ["Title", "Budget", "Populartiy"]
#html_popular_sorted = build_table(popular_movie, 'blue_dark')
#print(html_popular_sorted)

#clean_least_popular.columns = ["Title", "Budget", "Populartiy"]
#html_least_popular = build_table(clean_least_popular, 'blue_dark')
#print(html_least_popular)

<p><table border="0" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th style = "background-color: #305496;font-family: Century Gothic, sans-serif;font-size: medium;color: #FFFFFF;text-align: left;border-bottom: 2px solid #305496;padding: 0px 20px 0px 0px;width: auto">Title</th>
      <th style = "background-color: #305496;font-family: Century Gothic, sans-serif;font-size: medium;color: #FFFFFF;text-align: left;border-bottom: 2px solid #305496;padding: 0px 20px 0px 0px;width: auto">Budget</th>
      <th style = "background-color: #305496;font-family: Century Gothic, sans-serif;font-size: medium;color: #FFFFFF;text-align: left;border-bottom: 2px solid #305496;padding: 0px 20px 0px 0px;width: auto">Populartiy</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Sex and Death 101</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">5</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">13.981</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Chestnut: Hero of Central Park</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">6</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">12.673</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Brian Banks</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">10</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">56.422</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Sanctum</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">30</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">17.091</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Rugrats in Paris: The Movie</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">30</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">13.908</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Sí, Mi Amor</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">5000</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">39.666</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Primer</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">7000</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">15.648</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">King Kong vs. Godzilla</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">12000</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">15.284</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">One Missed Call</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">20000</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">11.922</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">One Cut of the Dead</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">30000</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">14.53</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">The Blair Witch Project</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">60000</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">32.225</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Vixen!</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">76000</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">13.012</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">The Texas Chain Saw Massacre</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">85000</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">36.719</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">A Ghost Story</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">100000</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">17.981</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Facing the Giants</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">100000</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">26.62</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Another Earth</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">100000</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">14.96</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">The Gallows</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">100000</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">19.745</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Stitches</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">100000</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">20.636</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Night of the Living Dead</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">114000</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">17.821</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">The Villainess</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">125000</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">30.6</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">The Way of the Dragon</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">130000</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">15.931</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Open Water</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">130000</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">18.014</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Megalodon</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">130178</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">45.816</td>
    </tr>
    <tr>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">In the Mood for Love</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">150000</td>
      <td style = "background-color: white; color: black;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">15.823</td>
    </tr>
    <tr>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">Children of Heaven</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">180000</td>
      <td style = "background-color: #D9E1F2;font-family: Century Gothic, sans-serif;font-size: medium;text-align: left;padding: 0px 20px 0px 0px;width: auto">27.619</td>
    </tr>
  </tbody>
</table></p>